version: "3.8"

services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres_db
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: on-failure

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672" # for apps
      - "15672:15672" # for web interface
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    restart: on-failure

  main-service:
    build:
      context: .
      dockerfile: Dockerfile
    command: /app/main-service
    env_file:
      - ./.env
    depends_on:
      - postgres
      - rabbitmq
    restart: on-failure

  worker-service:
    build:
      context: .
      dockerfile: Dockerfile
    command: /app/worker-service
    depends_on:
      - postgres
      - rabbitmq
    restart: on-failure

volumes:
  postgres-data:
